#!/bin/bash

# sets the environment to work using Andrew Morton great patch scripts

# run it in the top directory, like:
#  . utils/psenv


# create the directories
for i in ps/pc ps/patches ps/txt; do
	if [ ! -d $i ]; then
		mkdir -p -v $i
	fi
done


PATH=/root/bin/patch-scripts:$PATH
PATCHSCRIPTS=./ps

export PATH
export PATCHSCRIPTS

